version: 2
jobs:
  build:
    working_directory: ~/circleci-gh-pages
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: bundle install
      - run: "./render.rb all"
      - run: sudo apt-get update && sudo apt-get install -y awscli
      - run: aws --region eu-west-1 s3 sync ~/circleci-gh-pages/deploy/ s3://developer-pages.neo4j.com
