version: 2
jobs:
  build:
    working_directory: ~/circleci-gh-pages
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: bundle install
      - run: "./render.rb all"
      - store_artifacts:
          path: ~/circleci-gh-pages/
