version: 2
jobs:
  build:
    working_directory: ~/circleci-gh-pages
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: bundle install
      - run: "./render_local.rb all"
      - run: sudo apt-get update && sudo apt-get install -y awscli
      - run: cp -r ~/circleci-gh-pages/assets/ ~/circleci-gh-pages/deploy
      - run: aws --region eu-west-1 s3 sync ~/circleci-gh-pages/deploy/ s3://developer-pages.neo4j.com/developer/ --delete
  publish:
    working_directory: ~/circleci-publish
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - run: echo "mark" > ~/circleci-publish/mark.txt

workflows:
  version: 2
  build-gh-pages:
    jobs:
      - build
  publish-to-website:
    jobs:
      - publish
